name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        crate: [marquee_manager_rs, retroachievements_rs, utility_rs]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: rust/${{ matrix.crate }}
      run: cargo build --verbose
    - name: Run tests
      working-directory: rust/${{ matrix.crate }}
      run: cargo test --verbose
